/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mylibrary.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mylibrary.bean.Funcionario;
import mylibrary.bean.Endereco;
import mylibrary.dao.FuncionarioDao;

/**
 *
 * @author Michelle
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    private FuncionarioDao dao; 
            
    /**
     * Creates new form CadastroAluno
     */
    public CadastroFuncionario() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        dao = new FuncionarioDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JLayeredPane();
        lbNome = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        lbCpf = new javax.swing.JLabel();
        cpf = new javax.swing.JFormattedTextField();
        lbTel = new javax.swing.JLabel();
        tel = new javax.swing.JFormattedTextField();
        lbEmail = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        lbRua = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        lbBairro = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        lbCidade = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        lbEstado = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox();
        lbSetor = new javax.swing.JLabel();
        setor = new javax.swing.JComboBox();
        cancelar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        lbNumero = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        lbSenha = new javax.swing.JLabel();
        lbCargo = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox();
        senha = new javax.swing.JPasswordField();
        title = new javax.swing.JLabel();
        pesquisar = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lbNome.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 51, 51));
        lbNome.setText("Nome:");
        container.add(lbNome);
        lbNome.setBounds(20, 80, 60, 20);

        nome.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        nome.setForeground(new java.awt.Color(0, 51, 51));
        container.add(nome);
        nome.setBounds(80, 70, 350, 30);

        lbCpf.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbCpf.setForeground(new java.awt.Color(0, 51, 51));
        lbCpf.setText("CPF:");
        container.add(lbCpf);
        lbCpf.setBounds(30, 120, 40, 20);

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpf.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        container.add(cpf);
        cpf.setBounds(80, 110, 130, 30);

        lbTel.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbTel.setForeground(new java.awt.Color(0, 51, 51));
        lbTel.setText("Celular:");
        container.add(lbTel);
        lbTel.setBounds(220, 120, 70, 20);

        try {
            tel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tel.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        container.add(tel);
        tel.setBounds(300, 110, 130, 30);

        lbEmail.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(0, 51, 51));
        lbEmail.setText("Email:");
        container.add(lbEmail);
        lbEmail.setBounds(20, 160, 60, 20);

        email.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 51, 51));
        container.add(email);
        email.setBounds(80, 150, 350, 30);

        lbRua.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbRua.setForeground(new java.awt.Color(0, 51, 51));
        lbRua.setText("Rua:");
        container.add(lbRua);
        lbRua.setBounds(30, 200, 40, 20);

        rua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        rua.setForeground(new java.awt.Color(0, 51, 51));
        container.add(rua);
        rua.setBounds(80, 190, 270, 30);

        lbBairro.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbBairro.setForeground(new java.awt.Color(0, 51, 51));
        lbBairro.setText("Bairro:");
        container.add(lbBairro);
        lbBairro.setBounds(20, 240, 60, 20);

        bairro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        bairro.setForeground(new java.awt.Color(0, 51, 51));
        container.add(bairro);
        bairro.setBounds(80, 230, 130, 30);

        lbCidade.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbCidade.setForeground(new java.awt.Color(0, 51, 51));
        lbCidade.setText("Cidade:");
        container.add(lbCidade);
        lbCidade.setBounds(220, 240, 70, 20);

        cidade.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cidade.setForeground(new java.awt.Color(0, 51, 51));
        container.add(cidade);
        cidade.setBounds(300, 230, 130, 30);

        lbEstado.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(0, 51, 51));
        lbEstado.setText("UF:");
        container.add(lbEstado);
        lbEstado.setBounds(40, 320, 30, 20);

        estado.setBackground(new java.awt.Color(204, 255, 255));
        estado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paraíba" }));
        container.add(estado);
        estado.setBounds(80, 310, 130, 30);

        lbSetor.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbSetor.setForeground(new java.awt.Color(0, 51, 51));
        lbSetor.setText("Setor:");
        container.add(lbSetor);
        lbSetor.setBounds(240, 320, 60, 20);

        setor.setBackground(new java.awt.Color(204, 255, 255));
        setor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        setor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biblioteca" }));
        container.add(setor);
        setor.setBounds(300, 310, 130, 30);

        cancelar.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 0, 0));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/9iRadXL6T.png"))); // NOI18N
        cancelar.setText("Remover");
        container.add(cancelar);
        cancelar.setBounds(300, 390, 130, 40);

        editar.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        editar.setForeground(new java.awt.Color(51, 153, 255));
        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/edit.png"))); // NOI18N
        editar.setText("Editar");
        container.add(editar);
        editar.setBounds(160, 390, 130, 40);

        salvar.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        salvar.setForeground(new java.awt.Color(51, 204, 0));
        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/ok.png"))); // NOI18N
        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        container.add(salvar);
        salvar.setBounds(20, 390, 130, 40);

        lbNumero.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(0, 51, 51));
        lbNumero.setText("Nº:");
        container.add(lbNumero);
        lbNumero.setBounds(360, 190, 30, 28);

        numero.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        container.add(numero);
        numero.setBounds(390, 190, 40, 30);

        lbSenha.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(0, 51, 51));
        lbSenha.setText("Digite sua Senha de Acesso:");
        container.add(lbSenha);
        lbSenha.setBounds(20, 360, 230, 20);

        lbCargo.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        lbCargo.setForeground(new java.awt.Color(0, 51, 51));
        lbCargo.setText("Cargo:");
        container.add(lbCargo);
        lbCargo.setBounds(20, 280, 60, 20);

        cargo.setBackground(new java.awt.Color(204, 255, 255));
        cargo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        cargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assistente", "Bibliotecário", "Professor", "Cordenador" }));
        cargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoActionPerformed(evt);
            }
        });
        container.add(cargo);
        cargo.setBounds(80, 270, 350, 30);

        senha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        container.add(senha);
        senha.setBounds(260, 350, 170, 30);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/cadFunc.png"))); // NOI18N
        container.add(title);
        title.setBounds(50, 20, 340, 40);

        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/pesquisa.png"))); // NOI18N
        container.add(pesquisar);
        pesquisar.setBounds(400, 20, 30, 30);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/lih.jpg"))); // NOI18N
        container.add(img);
        img.setBounds(0, 0, 450, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed

    }//GEN-LAST:event_salvarActionPerformed

    private void cargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastroFuncionario().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CadastroFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox cargo;
    private javax.swing.JTextField cidade;
    private javax.swing.JLayeredPane container;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JButton editar;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox estado;
    private javax.swing.JLabel img;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbCargo;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbSetor;
    private javax.swing.JLabel lbTel;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JLabel pesquisar;
    private javax.swing.JTextField rua;
    private javax.swing.JButton salvar;
    private javax.swing.JPasswordField senha;
    private javax.swing.JComboBox setor;
    private javax.swing.JFormattedTextField tel;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
