/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mylibrary.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mylibrary.dao.FuncionarioDao;

/**
 *
 * @author Michelle
 */
public class Login extends javax.swing.JFrame {
    private FuncionarioDao dao;
    /**
     * Creates new form Login
     */
    public Login() throws IOException {
        initComponents();
        setLocationRelativeTo(null);
        dao = new FuncionarioDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JLayeredPane();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        senha = new javax.swing.JPasswordField();
        entra = new javax.swing.JButton();
        login = new javax.swing.JFormattedTextField();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGB - Sistema de Gerenciamento para Bibliotecas");
        setResizable(false);

        lbLogin.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        lbLogin.setForeground(new java.awt.Color(0, 53, 53));
        lbLogin.setText("   Login:");
        container.add(lbLogin);
        lbLogin.setBounds(460, 230, 200, 70);

        lbSenha.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        lbSenha.setForeground(new java.awt.Color(0, 53, 53));
        lbSenha.setText("Senha:");
        container.add(lbSenha);
        lbSenha.setBounds(490, 310, 165, 50);

        senha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        senha.setForeground(new java.awt.Color(0, 51, 51));
        container.add(senha);
        senha.setBounds(670, 310, 150, 40);

        entra.setBackground(new java.awt.Color(204, 255, 255));
        entra.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        entra.setForeground(new java.awt.Color(0, 153, 0));
        entra.setText("Entrar");
        entra.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        entra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entraActionPerformed(evt);
            }
        });
        container.add(entra);
        entra.setBounds(710, 360, 110, 40);

        try {
            login.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        login.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        container.add(login);
        login.setBounds(670, 250, 150, 40);

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/Alien Ink 2560X1600 Abstract Background.jpg"))); // NOI18N
        container.add(img);
        img.setBounds(0, 0, 1325, 670);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 1325, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entraActionPerformed
        if (login.getText().equals("000.000.000-00") && new String(senha.getPassword()).equals("admin")) {
            new Sistema().setVisible(true);   
        }
        dispose();
    }//GEN-LAST:event_entraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Login().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane container;
    private javax.swing.JButton entra;
    private javax.swing.JLabel img;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JFormattedTextField login;
    private javax.swing.JPasswordField senha;
    // End of variables declaration//GEN-END:variables
}
