package mylibrary.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JLayeredPane();
        title = new javax.swing.JLabel();
        devolucao = new javax.swing.JButton();
        cadastroUser = new javax.swing.JButton();
        cadastroLivro = new javax.swing.JButton();
        emprestimo = new javax.swing.JButton();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SGB - Sistema de Gerenciamento para Bibliotecas");
        setResizable(false);

        title.setFont(new java.awt.Font("Bauhaus 93", 0, 48)); // NOI18N
        title.setForeground(new java.awt.Color(153, 255, 255));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/titlw.png"))); // NOI18N
        container.add(title);
        title.setBounds(180, 60, 870, 80);

        devolucao.setBackground(new java.awt.Color(204, 255, 255));
        devolucao.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        devolucao.setForeground(new java.awt.Color(0, 51, 51));
        devolucao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/curtir (1).png"))); // NOI18N
        devolucao.setText("  Devolução de Livro");
        devolucao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        devolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucaoActionPerformed(evt);
            }
        });
        container.add(devolucao);
        devolucao.setBounds(660, 400, 400, 150);

        cadastroUser.setBackground(new java.awt.Color(204, 255, 255));
        cadastroUser.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        cadastroUser.setForeground(new java.awt.Color(0, 51, 51));
        cadastroUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/usrcad.png"))); // NOI18N
        cadastroUser.setText("Cadastro de Usuário");
        cadastroUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroUserActionPerformed(evt);
            }
        });
        container.add(cadastroUser);
        cadastroUser.setBounds(190, 180, 400, 150);

        cadastroLivro.setBackground(new java.awt.Color(204, 255, 255));
        cadastroLivro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        cadastroLivro.setForeground(new java.awt.Color(0, 51, 51));
        cadastroLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/_Books_glass_folder.png"))); // NOI18N
        cadastroLivro.setText("    Cadastro de Livro");
        cadastroLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastroLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroLivroActionPerformed(evt);
            }
        });
        container.add(cadastroLivro);
        cadastroLivro.setBounds(190, 400, 400, 150);

        emprestimo.setBackground(new java.awt.Color(204, 255, 255));
        emprestimo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        emprestimo.setForeground(new java.awt.Color(0, 51, 51));
        emprestimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/registro.png"))); // NOI18N
        emprestimo.setText(" Emprestimo de Livro");
        emprestimo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        emprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emprestimoActionPerformed(evt);
            }
        });
        emprestimo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emprestimoKeyPressed(evt);
            }
        });
        container.add(emprestimo);
        emprestimo.setBounds(660, 180, 400, 150);

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mylibrary/gui/image/sistela.jpg"))); // NOI18N
        container.add(imgFundo);
        imgFundo.setBounds(0, 0, 1300, 680);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 1296, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void devolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucaoActionPerformed

    }//GEN-LAST:event_devolucaoActionPerformed

    private void cadastroUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroUserActionPerformed
        new OpcaoUser().setVisible(true);
    }//GEN-LAST:event_cadastroUserActionPerformed

    private void cadastroLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroLivroActionPerformed

    }//GEN-LAST:event_cadastroLivroActionPerformed

    private void emprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emprestimoActionPerformed

    }//GEN-LAST:event_emprestimoActionPerformed

    private void emprestimoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emprestimoKeyPressed
        
    }//GEN-LAST:event_emprestimoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroLivro;
    private javax.swing.JButton cadastroUser;
    private javax.swing.JLayeredPane container;
    private javax.swing.JButton devolucao;
    private javax.swing.JButton emprestimo;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
